SystemJS.config({
  paths: {
    "github:": "jspm_packages/github/",
    "npm:": "jspm_packages/npm/",
    "mdk:": "jspm_packages/mdk/",
    "local:": "jspm_packages/local/",
    "app/": "app/"
  },
  browserConfig: {
    "baseURL": "build",
    "bundles": {
      "dep.js": [
        "npm:typescript@2.0.2/lib/lib.es6.d.ts!github:frankwallis/plugin-typescript@5.1.1/plugin.js",
        "npm:typescript@2.0.2.json",
        "github:frankwallis/plugin-typescript@5.1.1.json",
        "npm:ionic-native@1.3.21/dist/index.js",
        "npm:ionic-native@1.3.21.json",
        "npm:ionic-native@1.3.21/dist/plugins/plugin.js",
        "npm:rxjs@5.0.0-beta.6/Observable.js",
        "npm:rxjs@5.0.0-beta.6.json",
        "npm:rxjs@5.0.0-beta.6/util/toSubscriber.js",
        "npm:rxjs@5.0.0-beta.6/symbol/rxSubscriber.js",
        "npm:rxjs@5.0.0-beta.6/util/root.js",
        "npm:rxjs@5.0.0-beta.6/Subscriber.js",
        "npm:rxjs@5.0.0-beta.6/Observer.js",
        "npm:rxjs@5.0.0-beta.6/Subscription.js",
        "npm:rxjs@5.0.0-beta.6/util/UnsubscriptionError.js",
        "npm:rxjs@5.0.0-beta.6/util/errorObject.js",
        "npm:rxjs@5.0.0-beta.6/util/tryCatch.js",
        "npm:rxjs@5.0.0-beta.6/util/isFunction.js",
        "npm:rxjs@5.0.0-beta.6/util/isObject.js",
        "npm:rxjs@5.0.0-beta.6/util/isArray.js",
        "npm:rxjs@5.0.0-beta.6/symbol/observable.js",
        "npm:ionic-native@1.3.21/dist/util.js",
        "npm:ionic-native@1.3.21/dist/plugins/zip.js",
        "npm:ionic-native@1.3.21/dist/plugins/youtube-video-player.js",
        "npm:ionic-native@1.3.21/dist/plugins/webintent.js",
        "npm:ionic-native@1.3.21/dist/plugins/video-player.js",
        "npm:ionic-native@1.3.21/dist/plugins/video-editor.js",
        "npm:ionic-native@1.3.21/dist/plugins/vibration.js",
        "npm:ionic-native@1.3.21/dist/plugins/twitter-connect.js",
        "npm:ionic-native@1.3.21/dist/plugins/text-to-speech.js",
        "npm:ionic-native@1.3.21/dist/plugins/touchid.js",
        "npm:ionic-native@1.3.21/dist/plugins/toast.js",
        "npm:ionic-native@1.3.21/dist/plugins/3dtouch.js",
        "npm:ionic-native@1.3.21/dist/plugins/streaming-media.js",
        "npm:ionic-native@1.3.21/dist/plugins/statusbar.js",
        "npm:ionic-native@1.3.21/dist/plugins/sqlite.js",
        "npm:ionic-native@1.3.21/dist/plugins/splashscreen.js",
        "npm:ionic-native@1.3.21/dist/plugins/spinnerdialog.js",
        "npm:ionic-native@1.3.21/dist/plugins/socialsharing.js",
        "npm:ionic-native@1.3.21/dist/plugins/sms.js",
        "npm:ionic-native@1.3.21/dist/plugins/sim.js",
        "npm:ionic-native@1.3.21/dist/plugins/shake.js",
        "npm:ionic-native@1.3.21/dist/plugins/securestorage.js",
        "npm:ionic-native@1.3.21/dist/plugins/screenshot.js",
        "npm:ionic-native@1.3.21/dist/plugins/safari-view-controller.js",
        "npm:ionic-native@1.3.21/dist/plugins/push.js",
        "npm:ionic-native@1.3.21/dist/plugins/printer.js",
        "npm:ionic-native@1.3.21/dist/plugins/power-management.js",
        "npm:ionic-native@1.3.21/dist/plugins/pin-dialog.js",
        "npm:ionic-native@1.3.21/dist/plugins/pay-pal.js",
        "npm:ionic-native@1.3.21/dist/plugins/screen-orientation.js",
        "npm:ionic-native@1.3.21/dist/plugins/photo-viewer.js",
        "npm:ionic-native@1.3.21/dist/plugins/onesignal.js",
        "npm:ionic-native@1.3.21/dist/plugins/nfc.js",
        "npm:ionic-native@1.3.21/dist/plugins/network.js",
        "npm:ionic-native@1.3.21/dist/plugins/music-controls.js",
        "npm:ionic-native@1.3.21/dist/plugins/mixpanel.js",
        "npm:ionic-native@1.3.21/dist/plugins/media.js",
        "npm:ionic-native@1.3.21/dist/plugins/market.js",
        "npm:ionic-native@1.3.21/dist/plugins/nativestorage.js",
        "npm:ionic-native@1.3.21/dist/plugins/native-page-transitions.js",
        "npm:ionic-native@1.3.21/dist/plugins/native-audio.js",
        "npm:ionic-native@1.3.21/dist/plugins/media-capture.js",
        "npm:ionic-native@1.3.21/dist/plugins/localnotifications.js",
        "npm:ionic-native@1.3.21/dist/plugins/launchnavigator.js",
        "npm:ionic-native@1.3.21/dist/plugins/keyboard.js",
        "npm:ionic-native@1.3.21/dist/plugins/is-debug.js",
        "npm:ionic-native@1.3.21/dist/plugins/instagram.js",
        "npm:ionic-native@1.3.21/dist/plugins/insomnia.js",
        "npm:ionic-native@1.3.21/dist/plugins/inapppurchase.js",
        "npm:ionic-native@1.3.21/dist/plugins/inappbrowser.js",
        "npm:ionic-native@1.3.21/dist/plugins/imageresizer.js",
        "npm:ionic-native@1.3.21/dist/plugins/imagepicker.js",
        "npm:ionic-native@1.3.21/dist/plugins/ibeacon.js",
        "npm:ionic-native@1.3.21/dist/plugins/httpd.js",
        "npm:ionic-native@1.3.21/dist/plugins/hotspot.js",
        "npm:ionic-native@1.3.21/dist/plugins/googleanalytics.js",
        "npm:ionic-native@1.3.21/dist/plugins/googlemaps.js",
        "npm:ionic-native@1.3.21/dist/plugins/google-plus.js",
        "npm:ionic-native@1.3.21/dist/plugins/globalization.js",
        "npm:ionic-native@1.3.21/dist/plugins/geolocation.js",
        "npm:ionic-native@1.3.21/dist/plugins/geofence.js",
        "npm:ionic-native@1.3.21/dist/plugins/flashlight.js",
        "npm:ionic-native@1.3.21/dist/plugins/filetransfer.js",
        "npm:ionic-native@1.3.21/dist/plugins/file-opener.js",
        "npm:ionic-native@1.3.21/dist/plugins/file-chooser.js",
        "npm:ionic-native@1.3.21/dist/plugins/file.js",
        "npm:ionic-native@1.3.21/dist/plugins/facebook.js",
        "npm:ionic-native@1.3.21/dist/plugins/estimote-beacons.js",
        "npm:ionic-native@1.3.21/dist/plugins/emailcomposer.js",
        "npm:ionic-native@1.3.21/dist/plugins/dialogs.js",
        "npm:ionic-native@1.3.21/dist/plugins/diagnostic.js",
        "npm:ionic-native@1.3.21/dist/plugins/deviceorientation.js",
        "npm:ionic-native@1.3.21/dist/plugins/devicemotion.js",
        "npm:ionic-native@1.3.21/dist/plugins/deviceaccounts.js",
        "npm:ionic-native@1.3.21/dist/plugins/device.js",
        "npm:ionic-native@1.3.21/dist/plugins/deeplinks.js",
        "npm:ionic-native@1.3.21/dist/plugins/dbmeter.js",
        "npm:ionic-native@1.3.21/dist/plugins/datepicker.js",
        "npm:ionic-native@1.3.21/dist/plugins/crop.js",
        "npm:ionic-native@1.3.21/dist/plugins/contacts.js",
        "npm:ionic-native@1.3.21/dist/plugins/code-push.js",
        "npm:ionic-native@1.3.21/dist/plugins/clipboard.js",
        "npm:ionic-native@1.3.21/dist/plugins/card-io.js",
        "npm:ionic-native@1.3.21/dist/plugins/camera-preview.js",
        "npm:ionic-native@1.3.21/dist/plugins/camera.js",
        "npm:ionic-native@1.3.21/dist/plugins/call-number.js",
        "npm:ionic-native@1.3.21/dist/plugins/calendar.js",
        "npm:ionic-native@1.3.21/dist/plugins/bluetoothserial.js",
        "npm:ionic-native@1.3.21/dist/plugins/ble.js",
        "npm:ionic-native@1.3.21/dist/plugins/brightness.js",
        "npm:ionic-native@1.3.21/dist/plugins/batterystatus.js",
        "npm:ionic-native@1.3.21/dist/plugins/base64togallery.js",
        "npm:ionic-native@1.3.21/dist/plugins/barcodescanner.js",
        "npm:ionic-native@1.3.21/dist/plugins/backgroundmode.js",
        "npm:ionic-native@1.3.21/dist/plugins/background-geolocation.js",
        "npm:ionic-native@1.3.21/dist/plugins/badge.js",
        "npm:ionic-native@1.3.21/dist/plugins/appversion.js",
        "npm:ionic-native@1.3.21/dist/plugins/apprate.js",
        "npm:ionic-native@1.3.21/dist/plugins/appavailability.js",
        "npm:ionic-native@1.3.21/dist/plugins/android-fingerprint-auth.js",
        "npm:ionic-native@1.3.21/dist/plugins/admob.js",
        "npm:ionic-native@1.3.21/dist/plugins/actionsheet.js",
        "npm:ionic-native@1.3.21/dist/ng1.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/index.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853.json",
        "github:jspm/nodelibs-process@0.2.0-alpha/process.js",
        "github:jspm/nodelibs-process@0.2.0-alpha.json",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/transitions/transition-wp.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/transitions/page-transition.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/transitions/transition.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/animations/animation.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/util.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/dom.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/content/content.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/view-controller.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-params.js",
        "npm:@angular/core@2.0.0-rc.4/index.js",
        "npm:@angular/core@2.0.0-rc.4.json",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_player.js",
        "npm:zone.js@0.6.17/dist/zone.js",
        "npm:zone.js@0.6.17.json",
        "npm:reflect-metadata@0.1.8/Reflect.js",
        "npm:reflect-metadata@0.1.8.json",
        "npm:@angular/core@2.0.0-rc.4/src/facade/lang.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/exceptions.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/exception_handler.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/collection.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/metadata.js",
        "npm:@angular/core@2.0.0-rc.4/private_export.js",
        "npm:@angular/core@2.0.0-rc.4/src/util/decorators.js",
        "npm:@angular/core@2.0.0-rc.4/src/security.js",
        "npm:@angular/core@2.0.0-rc.4/src/render/api.js",
        "npm:@angular/core@2.0.0-rc.4/src/reflection/reflector_reader.js",
        "npm:@angular/core@2.0.0-rc.4/src/reflection/reflection_capabilities.js",
        "npm:@angular/core@2.0.0-rc.4/src/reflection/reflection.js",
        "npm:@angular/core@2.0.0-rc.4/src/reflection/reflector.js",
        "npm:@angular/core@2.0.0-rc.4/src/profile/wtf_init.js",
        "npm:@angular/core@2.0.0-rc.4/src/metadata/view.js",
        "npm:@angular/core@2.0.0-rc.4/src/metadata/lifecycle_hooks.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/view_utils.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/exceptions.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/element.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/view_type.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/view_container_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/profile/profile.js",
        "npm:@angular/core@2.0.0-rc.4/src/profile/wtf_impl.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/element_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/decorators.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/metadata.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/change_detection_util.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/change_detection.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/constants.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/change_detector_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/keyvalue_differs.js",
        "npm:@angular/core@2.0.0-rc.4/src/di.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/opaque_token.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/reflective_exceptions.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/reflective_key.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/forward_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/reflective_provider.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/provider_util.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/provider.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/reflective_injector.js",
        "npm:@angular/core@2.0.0-rc.4/src/di/injector.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/iterable_differs.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/default_keyvalue_differ.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection/differs/default_iterable_differ.js",
        "npm:@angular/core@2.0.0-rc.4/src/application_tokens.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/view.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/active_animation_players_map.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_group_player.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/math.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/element_injector.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/debug_context.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/view_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/async.js",
        "npm:@angular/core@2.0.0-rc.4/src/facade/promise.js",
        "npm:rxjs@5.0.0-beta.6/operator/toPromise.js",
        "npm:rxjs@5.0.0-beta.6/observable/PromiseObservable.js",
        "npm:rxjs@5.0.0-beta.6/Subject.js",
        "npm:rxjs@5.0.0-beta.6/util/ObjectUnsubscribedError.js",
        "npm:rxjs@5.0.0-beta.6/util/throwError.js",
        "npm:rxjs@5.0.0-beta.6/SubjectSubscription.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/template_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/component_resolver.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/component_factory.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/component_factory_resolver.js",
        "npm:@angular/core@2.0.0-rc.4/src/debug/debug_renderer.js",
        "npm:@angular/core@2.0.0-rc.4/src/debug/debug_node.js",
        "npm:@angular/core@2.0.0-rc.4/src/console.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_styles.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_style_util.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_constants.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_sequence_player.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_keyframe.js",
        "npm:@angular/core@2.0.0-rc.4/src/animation/animation_driver.js",
        "npm:@angular/core@2.0.0-rc.4/src/application_common_providers.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/dynamic_component_loader.js",
        "npm:@angular/core@2.0.0-rc.4/src/application_ref.js",
        "npm:@angular/core@2.0.0-rc.4/src/zone/ng_zone.js",
        "npm:@angular/core@2.0.0-rc.4/src/zone/ng_zone_impl.js",
        "npm:@angular/core@2.0.0-rc.4/src/testability/testability.js",
        "npm:@angular/core@2.0.0-rc.4/src/platform_common_providers.js",
        "npm:@angular/core@2.0.0-rc.4/src/platform_directives_and_pipes.js",
        "npm:@angular/core@2.0.0-rc.4/src/change_detection.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/systemjs_component_resolver.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/query_list.js",
        "npm:@angular/core@2.0.0-rc.4/src/linker/compiler.js",
        "npm:@angular/core@2.0.0-rc.4/src/render.js",
        "npm:@angular/core@2.0.0-rc.4/src/zone.js",
        "npm:@angular/core@2.0.0-rc.4/src/util.js",
        "npm:@angular/core@2.0.0-rc.4/src/metadata.js",
        "npm:@angular/core@2.0.0-rc.4/src/metadata/directives.js",
        "npm:@angular/core@2.0.0-rc.4/src/metadata/di.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tabs/tabs.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tabs/tab-highlight.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tabs/tab-button.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tabs/tab.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-controller-base.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/swipe-back.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/slide-edge-gesture.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/slide-gesture.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/datetime-util.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/drag-gesture.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/recognizers.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/ui-event-manager.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-interfaces.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-controller.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/ion.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/config/bootstrap.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tap-click/tap-click.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tap-click/ripple.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/tap-click/activator.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/config/config.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/platform/platform.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/app/app.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-portal.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/keyboard.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/key.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/form.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/gesture-controller.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/click-block.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/index.js",
        "npm:@angular/platform-browser@2.0.0-rc.4.json",
        "npm:@angular/platform-browser@2.0.0-rc.4/private_export.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/shared_styles_host.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/dom_tokens.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/dom_adapter.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/lang.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/collection.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/dom_events.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/event_manager.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/exceptions.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/exception_handler.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/dom_renderer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/util.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/core_private.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/debug/ng_probe.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/worker_app.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/worker_adapter.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/renderer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/event_deserializer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/serializer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/serialized_types.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/render_store.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/messaging_api.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/message_bus.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/client_message_broker.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/async.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/promise.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/service_message_broker.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/post_message_bus.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/shared/api.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/security/dom_sanitization_service.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/security/url_sanitizer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/security/style_sanitizer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/security/html_sanitizer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/key_events.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/hammer_gestures.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/events/hammer_common.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/testability.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/location/browser_platform_location.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/location/history.js",
        "npm:@angular/common@2.0.0-rc.4/index.js",
        "npm:@angular/common@2.0.0-rc.4.json",
        "npm:@angular/common@2.0.0-rc.4/src/localization.js",
        "npm:@angular/common@2.0.0-rc.4/src/location.js",
        "npm:@angular/common@2.0.0-rc.4/src/location/location.js",
        "npm:@angular/common@2.0.0-rc.4/src/location/location_strategy.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/async.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/promise.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/lang.js",
        "npm:@angular/common@2.0.0-rc.4/src/location/path_location_strategy.js",
        "npm:@angular/common@2.0.0-rc.4/src/location/platform_location.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/exceptions.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/exception_handler.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/collection.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
        "npm:@angular/common@2.0.0-rc.4/src/location/hash_location_strategy.js",
        "npm:@angular/common@2.0.0-rc.4/src/common_directives.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/validators.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/model.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/validators.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/select_control_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/control_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_model.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/shared.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/select_multiple_control_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/radio_control_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/abstract_control_directive.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/number_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/normalize_validator.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/default_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/checkbox_value_accessor.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_form_model.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/control_container.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_form_control.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_form.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control_status.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control_name.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives/ng_control_group.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/directives.js",
        "npm:@angular/common@2.0.0-rc.4/src/forms-deprecated/form_builder.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_template_outlet.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_switch.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_style.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_plural.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_if.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_for.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/ng_class.js",
        "npm:@angular/common@2.0.0-rc.4/src/directives/core_directives.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/uppercase_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/invalid_pipe_argument_exception.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/slice_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/replace_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/number_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/facade/intl.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/lowercase_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/json_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/i18n_select_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/i18n_plural_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/date_pipe.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/common_pipes.js",
        "npm:@angular/common@2.0.0-rc.4/src/pipes/async_pipe.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/browser_adapter.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/generic_browser_adapter.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/web_animations_driver.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/web_animations_player.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/worker_render.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/renderer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/event_dispatcher.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/event_serializer.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/location_providers.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/ui/platform_location.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/location_providers.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/web_workers/worker/platform_location.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/dom/debug/by.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/tools/tools.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/tools/common_tools.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/facade/browser.js",
        "npm:@angular/platform-browser@2.0.0-rc.4/src/browser/title.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/config/providers.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/translation/translate.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/toast/toast.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/toast/toast-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/scroll-view.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/popover/popover.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/popover/popover-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/backdrop/backdrop.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/picker/picker.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/picker/picker-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/modal/modal.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/modal/modal-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/menu/menu-controller.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/loading/loading.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/loading/loading-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/spinner/spinner.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/config/directives.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/chip/chip.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/typography/typography.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/show-hide-when/show-hide-when.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/navbar/navbar.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/toolbar/toolbar.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/icon/icon.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-push.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav-pop.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/nav/nav.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/searchbar/searchbar.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/debouncer.js",
        "npm:@angular/forms@0.2.0/index.js",
        "npm:@angular/forms@0.2.0.json",
        "npm:@angular/forms@0.2.0/src/forms.js",
        "npm:@angular/forms@0.2.0/src/form_providers.js",
        "npm:@angular/forms@0.2.0/src/form_builder.js",
        "npm:@angular/forms@0.2.0/src/model.js",
        "npm:@angular/forms@0.2.0/src/facade/lang.js",
        "npm:@angular/forms@0.2.0/src/facade/collection.js",
        "npm:@angular/forms@0.2.0/src/facade/async.js",
        "npm:@angular/forms@0.2.0/src/facade/promise.js",
        "npm:@angular/forms@0.2.0/src/directives/shared.js",
        "npm:@angular/forms@0.2.0/src/directives/select_multiple_control_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/directives/control_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/directives/select_control_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/directives/radio_control_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/directives/ng_control.js",
        "npm:@angular/forms@0.2.0/src/directives/abstract_control_directive.js",
        "npm:@angular/forms@0.2.0/src/facade/exceptions.js",
        "npm:@angular/forms@0.2.0/src/facade/exception_handler.js",
        "npm:@angular/forms@0.2.0/src/facade/base_wrapped_exception.js",
        "npm:@angular/forms@0.2.0/src/directives/number_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/directives/normalize_validator.js",
        "npm:@angular/forms@0.2.0/src/directives/default_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/directives/checkbox_value_accessor.js",
        "npm:@angular/forms@0.2.0/src/validators.js",
        "npm:@angular/forms@0.2.0/src/directives.js",
        "npm:@angular/forms@0.2.0/src/directives/validators.js",
        "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_group_name.js",
        "npm:@angular/forms@0.2.0/src/directives/control_container.js",
        "npm:@angular/forms@0.2.0/src/directives/abstract_form_group_directive.js",
        "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_group_directive.js",
        "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_control_name.js",
        "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_control_directive.js",
        "npm:@angular/forms@0.2.0/src/directives/reactive_directives/form_array_name.js",
        "npm:@angular/forms@0.2.0/src/directives/ng_model_group.js",
        "npm:@angular/forms@0.2.0/src/directives/ng_model.js",
        "npm:@angular/forms@0.2.0/src/directives/ng_form.js",
        "npm:@angular/forms@0.2.0/src/directives/ng_control_status.js",
        "npm:@angular/compiler@2.0.0-rc.4/index.js",
        "npm:@angular/compiler@2.0.0-rc.4.json",
        "npm:@angular/compiler@2.0.0-rc.4/compiler.js",
        "npm:@angular/compiler@2.0.0-rc.4/private_export.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/view_compiler.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/view_builder.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/util.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/identifiers.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/util.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/lang.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/collection.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/compile_metadata.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/url_resolver.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/selector.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/exceptions.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/exception_handler.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
        "npm:@angular/compiler@2.0.0-rc.4/core_private.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/output_ast.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/constants.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_view.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_query.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_pipe.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_method.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_element.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/template_ast.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/animation/animation_compiler.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/animation/animation_parser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/animation/styles_collection.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/animation/animation_ast.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/parse_util.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/math.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/view_binder.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/lifecycle_binder.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/event_binder.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/expression_converter.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/compile_binding.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_compiler/property_binder.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/config.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/template_parser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/provider_parser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/html_ast.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/style_url_resolver.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/template_preparser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/html_tags.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/schema/element_schema_registry.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/html_parser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/html_lexer.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/interpolation_config.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/chars.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/expression_parser/parser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/expression_parser/lexer.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/expression_parser/ast.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/style_compiler.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/shadow_css.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/schema/dom_element_schema_registry.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/schema/dom_security_schema.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/ts_emitter.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/abstract_emitter.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/path_util.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/metadata_resolver.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/view_resolver.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/pipe_resolver.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/directive_resolver.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/directive_lifecycle_reflector.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/assertions.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/i18n/xmb_serializer.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/i18n/message.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/i18n/message_extractor.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/i18n/shared.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/i18n/i18n_html_parser.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/i18n/expander.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/directive_normalizer.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/xhr.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/compiler.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/runtime_compiler.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/interpretive_view.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/output_interpreter.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/dart_emitter.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/async.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/facade/promise.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/output_jit.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/output/abstract_js_emitter.js",
        "npm:@angular/compiler@2.0.0-rc.4/src/offline_compiler.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/range/range.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/item/item.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/label/label.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/item/item-reorder.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/item/item-reorder-gesture.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/button/button.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/radio/radio-group.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/list/list.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/item/item-sliding-gesture.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/radio/radio-button.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/segment/segment.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/input/input.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/input/native-input.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/input/input-base.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/toggle/toggle.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/datetime/datetime.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/option/option.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/select/select.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/alert/alert.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/alert/alert-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/action-sheet/action-sheet.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/action-sheet/action-sheet-component.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/checkbox/checkbox.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/toolbar/toolbar-title.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/toolbar/toolbar-item.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/virtual-scroll/virtual-item.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/virtual-scroll/virtual-scroll.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/img/img.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/virtual-scroll/virtual-util.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/item/item-sliding.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/slides/slides.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/slides/swiper-widget.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/gesture.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/hammer.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/refresher/refresher-content.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/refresher/refresher.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/infinite-scroll/infinite-scroll-content.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/infinite-scroll/infinite-scroll.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/scroll/scroll.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/badge/badge.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/menu/menu-close.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/menu/menu-toggle.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/menu/menu.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/menu/menu-gestures.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/gestures/ionic-gesture-config.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/feature-detect.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/util/events.js",
        "npm:@angular/http@2.0.0-rc.4/index.js",
        "npm:@angular/http@2.0.0-rc.4.json",
        "npm:@angular/http@2.0.0-rc.4/http.js",
        "npm:@angular/http@2.0.0-rc.4/src/url_search_params.js",
        "npm:@angular/http@2.0.0-rc.4/src/facade/lang.js",
        "npm:@angular/http@2.0.0-rc.4/src/facade/collection.js",
        "npm:@angular/http@2.0.0-rc.4/src/static_response.js",
        "npm:@angular/http@2.0.0-rc.4/src/http_utils.js",
        "npm:@angular/http@2.0.0-rc.4/src/enums.js",
        "npm:@angular/http@2.0.0-rc.4/src/facade/exceptions.js",
        "npm:@angular/http@2.0.0-rc.4/src/facade/exception_handler.js",
        "npm:@angular/http@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
        "npm:@angular/http@2.0.0-rc.4/src/static_request.js",
        "npm:@angular/http@2.0.0-rc.4/src/headers.js",
        "npm:@angular/http@2.0.0-rc.4/src/interfaces.js",
        "npm:@angular/http@2.0.0-rc.4/src/http.js",
        "npm:@angular/http@2.0.0-rc.4/src/base_request_options.js",
        "npm:@angular/http@2.0.0-rc.4/src/base_response_options.js",
        "npm:@angular/http@2.0.0-rc.4/src/backends/xhr_backend.js",
        "npm:@angular/http@2.0.0-rc.4/src/backends/browser_xhr.js",
        "npm:@angular/http@2.0.0-rc.4/src/backends/jsonp_backend.js",
        "npm:@angular/http@2.0.0-rc.4/src/backends/browser_jsonp.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/index.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4.json",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/xhr/xhr_impl.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/promise.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/lang.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/xhr/xhr_cache.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/exceptions.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/exception_handler.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/collection.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/base_wrapped_exception.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/src/facade/async.js",
        "npm:@angular/platform-browser-dynamic@2.0.0-rc.4/core_private.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/transitions/transition-md.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/transitions/transition-ios.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/animations/builtins.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/platform/registry.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/config/modes.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/translation/translate_pipe.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/platform/storage.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/platform/storage/sql.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/platform/storage/storage.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/platform/storage/local-storage.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/components/menu/menu-types.js",
        "npm:ionic-angular@2.0.0-beta.11-201609011853/decorators/page.js",
        "jspm_packages/system.js",
        "github:jspm/nodelibs-fs@0.2.0-alpha/fs.js",
        "github:jspm/nodelibs-fs@0.2.0-alpha.json",
        "jspm_packages/system-polyfills.js",
        "github:frankwallis/plugin-typescript@5.1.1/plugin.js",
        "github:frankwallis/plugin-typescript@5.1.1/utils.js",
        "npm:typescript@2.0.2/lib/typescript.js",
        "npm:crypto-browserify@3.11.0/index.js",
        "npm:crypto-browserify@3.11.0.json",
        "npm:public-encrypt@4.0.0/browser.js",
        "npm:public-encrypt@4.0.0.json",
        "npm:public-encrypt@4.0.0/privateDecrypt.js",
        "github:jspm/nodelibs-buffer@0.2.0-alpha/global.js",
        "github:jspm/nodelibs-buffer@0.2.0-alpha.json",
        "npm:buffer@4.9.1/index.js",
        "npm:buffer@4.9.1.json",
        "npm:isarray@1.0.0/index.js",
        "npm:isarray@1.0.0.json",
        "npm:ieee754@1.1.6/index.js",
        "npm:ieee754@1.1.6.json",
        "npm:base64-js@1.1.2/lib/b64.js",
        "npm:base64-js@1.1.2.json",
        "npm:public-encrypt@4.0.0/withPublic.js",
        "npm:bn.js@4.11.6/lib/bn.js",
        "npm:bn.js@4.11.6.json",
        "npm:create-hash@1.1.2/browser.js",
        "npm:create-hash@1.1.2.json",
        "npm:cipher-base@1.0.2/index.js",
        "npm:cipher-base@1.0.2.json",
        "npm:string_decoder@0.10.31/index.js",
        "npm:string_decoder@0.10.31.json",
        "github:jspm/nodelibs-string_decoder@0.2.0-alpha.json",
        "npm:inherits@2.0.3/inherits_browser.js",
        "npm:inherits@2.0.3.json",
        "npm:stream-browserify@2.0.1/index.js",
        "npm:stream-browserify@2.0.1.json",
        "npm:readable-stream@2.1.5/passthrough.js",
        "npm:readable-stream@2.1.5.json",
        "npm:readable-stream@2.1.5/lib/_stream_passthrough.js",
        "npm:core-util-is@1.0.2/lib/util.js",
        "npm:core-util-is@1.0.2.json",
        "npm:readable-stream@2.1.5/lib/_stream_transform.js",
        "npm:readable-stream@2.1.5/lib/_stream_duplex.js",
        "npm:readable-stream@2.1.5/lib/_stream_writable.js",
        "npm:buffer-shims@1.0.0/index.js",
        "npm:buffer-shims@1.0.0.json",
        "github:jspm/nodelibs-events@0.2.0-alpha/events.js",
        "github:jspm/nodelibs-events@0.2.0-alpha.json",
        "npm:util-deprecate@1.0.2/browser.js",
        "npm:util-deprecate@1.0.2.json",
        "npm:process-nextick-args@1.0.7/index.js",
        "npm:process-nextick-args@1.0.7.json",
        "npm:readable-stream@2.1.5/lib/_stream_readable.js",
        "npm:readable-stream@2.1.5/lib/internal/streams/BufferList.js",
        "npm:readable-stream@2.1.5/transform.js",
        "npm:readable-stream@2.1.5/duplex.js",
        "npm:readable-stream@2.1.5/writable.js",
        "npm:readable-stream@2.1.5/readable.js",
        "github:jspm/nodelibs-stream@0.2.0-alpha.json",
        "npm:sha.js@2.4.5/index.js",
        "npm:sha.js@2.4.5.json",
        "npm:sha.js@2.4.5/sha512.js",
        "npm:sha.js@2.4.5/hash.js",
        "npm:sha.js@2.4.5/sha384.js",
        "npm:sha.js@2.4.5/sha256.js",
        "npm:sha.js@2.4.5/sha224.js",
        "npm:sha.js@2.4.5/sha1.js",
        "npm:sha.js@2.4.5/sha.js",
        "npm:ripemd160@1.0.1/lib/ripemd160.js",
        "npm:ripemd160@1.0.1.json",
        "npm:create-hash@1.1.2/md5.js",
        "npm:create-hash@1.1.2/helpers.js",
        "npm:browserify-rsa@4.0.1/index.js",
        "npm:browserify-rsa@4.0.1.json",
        "npm:randombytes@2.0.3/browser.js",
        "npm:randombytes@2.0.3.json",
        "npm:public-encrypt@4.0.0/xor.js",
        "npm:public-encrypt@4.0.0/mgf.js",
        "npm:parse-asn1@5.0.0/index.js",
        "npm:parse-asn1@5.0.0.json",
        "npm:pbkdf2@3.0.4/browser.js",
        "npm:pbkdf2@3.0.4.json",
        "npm:create-hmac@1.1.4/browser.js",
        "npm:create-hmac@1.1.4.json",
        "npm:browserify-aes@1.0.6/browser.js",
        "npm:browserify-aes@1.0.6.json",
        "npm:browserify-aes@1.0.6/modes.js",
        "npm:browserify-aes@1.0.6/decrypter.js",
        "npm:browserify-aes@1.0.6/modes/ctr.js",
        "npm:buffer-xor@1.0.3/index.js",
        "npm:buffer-xor@1.0.3.json",
        "npm:browserify-aes@1.0.6/modes/ofb.js",
        "npm:browserify-aes@1.0.6/modes/cfb1.js",
        "npm:browserify-aes@1.0.6/modes/cfb8.js",
        "npm:browserify-aes@1.0.6/modes/cfb.js",
        "npm:browserify-aes@1.0.6/modes/cbc.js",
        "npm:browserify-aes@1.0.6/modes/ecb.js",
        "npm:evp_bytestokey@1.0.0/index.js",
        "npm:evp_bytestokey@1.0.0.json",
        "npm:browserify-aes@1.0.6/authCipher.js",
        "npm:browserify-aes@1.0.6/ghash.js",
        "npm:browserify-aes@1.0.6/aes.js",
        "npm:browserify-aes@1.0.6/streamCipher.js",
        "npm:browserify-aes@1.0.6/encrypter.js",
        "npm:parse-asn1@5.0.0/fixProc.js",
        "npm:parse-asn1@5.0.0/aesid.json",
        "npm:parse-asn1@5.0.0/asn1.js",
        "npm:asn1.js@4.8.0/lib/asn1.js",
        "npm:asn1.js@4.8.0.json",
        "npm:asn1.js@4.8.0/lib/asn1/encoders/index.js",
        "npm:asn1.js@4.8.0/lib/asn1/encoders/pem.js",
        "npm:asn1.js@4.8.0/lib/asn1/encoders/der.js",
        "npm:asn1.js@4.8.0/lib/asn1/decoders/index.js",
        "npm:asn1.js@4.8.0/lib/asn1/decoders/pem.js",
        "npm:asn1.js@4.8.0/lib/asn1/decoders/der.js",
        "npm:asn1.js@4.8.0/lib/asn1/constants/index.js",
        "npm:asn1.js@4.8.0/lib/asn1/constants/der.js",
        "npm:asn1.js@4.8.0/lib/asn1/base/index.js",
        "npm:asn1.js@4.8.0/lib/asn1/base/node.js",
        "npm:minimalistic-assert@1.0.0/index.js",
        "npm:minimalistic-assert@1.0.0.json",
        "npm:asn1.js@4.8.0/lib/asn1/base/buffer.js",
        "npm:asn1.js@4.8.0/lib/asn1/base/reporter.js",
        "npm:asn1.js@4.8.0/lib/asn1/api.js",
        "github:jspm/nodelibs-vm@0.2.0-alpha/vm.js",
        "github:jspm/nodelibs-vm@0.2.0-alpha.json",
        "npm:public-encrypt@4.0.0/publicEncrypt.js",
        "npm:create-ecdh@4.0.0/browser.js",
        "npm:create-ecdh@4.0.0.json",
        "npm:elliptic@6.3.1/lib/elliptic.js",
        "npm:elliptic@6.3.1.json",
        "npm:elliptic@6.3.1/lib/elliptic/eddsa/index.js",
        "npm:elliptic@6.3.1/lib/elliptic/eddsa/signature.js",
        "npm:elliptic@6.3.1/lib/elliptic/eddsa/key.js",
        "npm:hash.js@1.0.3/lib/hash.js",
        "npm:hash.js@1.0.3.json",
        "npm:hash.js@1.0.3/lib/hash/hmac.js",
        "npm:hash.js@1.0.3/lib/hash/ripemd.js",
        "npm:hash.js@1.0.3/lib/hash/sha.js",
        "npm:hash.js@1.0.3/lib/hash/common.js",
        "npm:hash.js@1.0.3/lib/hash/utils.js",
        "npm:elliptic@6.3.1/lib/elliptic/ec/index.js",
        "npm:elliptic@6.3.1/lib/elliptic/ec/signature.js",
        "npm:elliptic@6.3.1/lib/elliptic/ec/key.js",
        "npm:elliptic@6.3.1/lib/elliptic/curves.js",
        "npm:elliptic@6.3.1/lib/elliptic/precomputed/secp256k1.js",
        "npm:elliptic@6.3.1/lib/elliptic/curve/index.js",
        "npm:elliptic@6.3.1/lib/elliptic/curve/edwards.js",
        "npm:elliptic@6.3.1/lib/elliptic/curve/mont.js",
        "npm:elliptic@6.3.1/lib/elliptic/curve/short.js",
        "npm:elliptic@6.3.1/lib/elliptic/curve/base.js",
        "npm:elliptic@6.3.1/lib/elliptic/hmac-drbg.js",
        "npm:brorand@1.0.6/index.js",
        "npm:brorand@1.0.6.json",
        "npm:elliptic@6.3.1/lib/elliptic/utils.js",
        "npm:elliptic@6.3.1/package.json",
        "npm:browserify-sign@4.0.0/browser.js",
        "npm:browserify-sign@4.0.0.json",
        "npm:browserify-sign@4.0.0/verify.js",
        "npm:browserify-sign@4.0.0/curves.js",
        "npm:browserify-sign@4.0.0/sign.js",
        "npm:browserify-sign@4.0.0/algos.js",
        "npm:diffie-hellman@5.0.2/browser.js",
        "npm:diffie-hellman@5.0.2.json",
        "npm:diffie-hellman@5.0.2/lib/dh.js",
        "npm:diffie-hellman@5.0.2/lib/generatePrime.js",
        "npm:miller-rabin@4.0.0/lib/mr.js",
        "npm:miller-rabin@4.0.0.json",
        "npm:diffie-hellman@5.0.2/lib/primes.json",
        "npm:browserify-cipher@1.0.0/browser.js",
        "npm:browserify-cipher@1.0.0.json",
        "npm:browserify-des@1.0.0/modes.js",
        "npm:browserify-des@1.0.0.json",
        "npm:browserify-des@1.0.0/index.js",
        "npm:des.js@1.0.0/lib/des.js",
        "npm:des.js@1.0.0.json",
        "npm:des.js@1.0.0/lib/des/ede.js",
        "npm:des.js@1.0.0/lib/des/cbc.js",
        "npm:des.js@1.0.0/lib/des/des.js",
        "npm:des.js@1.0.0/lib/des/cipher.js",
        "npm:des.js@1.0.0/lib/des/utils.js",
        "github:jspm/nodelibs-crypto@0.2.0-alpha.json",
        "npm:os-browserify@0.2.1/browser.js",
        "npm:os-browserify@0.2.1.json",
        "github:jspm/nodelibs-os@0.2.0-alpha.json",
        "github:frankwallis/plugin-typescript@5.1.1/format-errors.js",
        "github:frankwallis/plugin-typescript@5.1.1/factory.js",
        "github:frankwallis/plugin-typescript@5.1.1/type-checker.js",
        "github:frankwallis/plugin-typescript@5.1.1/compiler-host.js",
        "github:frankwallis/plugin-typescript@5.1.1/logger.js",
        "github:frankwallis/plugin-typescript@5.1.1/resolver.js",
        "github:frankwallis/plugin-typescript@5.1.1/transpiler.js"
      ]
    }
  },
  devConfig: {
    "map": {
      "plugin-typescript": "github:frankwallis/plugin-typescript@5.1.1"
    },
    "packages": {
      "github:frankwallis/plugin-typescript@5.1.1": {
        "map": {
          "typescript": "npm:typescript@2.0.2"
        }
      }
    }
  },
  transpiler: "plugin-typescript",
  typescriptOptions: {
    "module": "system",
    "noImplicitAny": true,
    "typeCheck": true,
    "tsconfig": true
  },
  packages: {
    "app": {
      "main": "app.ts",
      "defaultExtension": "ts",
      "format": "esm",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        }
      }
    }
  }
});

SystemJS.config({
  packageConfigPaths: [
    "github:*/*.json",
    "npm:@*/*.json",
    "npm:*.json",
    "mdk:*.json"
  ],
  map: {
    "@angular/common": "npm:@angular/common@2.0.0-rc.4",
    "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.4",
    "@angular/core": "npm:@angular/core@2.0.0-rc.4",
    "@angular/forms": "npm:@angular/forms@0.2.0",
    "@angular/http": "npm:@angular/http@2.0.0-rc.4",
    "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.4",
    "assert": "github:jspm/nodelibs-assert@0.2.0-alpha",
    "buffer": "github:jspm/nodelibs-buffer@0.2.0-alpha",
    "child_process": "github:jspm/nodelibs-child_process@0.2.0-alpha",
    "constants": "github:jspm/nodelibs-constants@0.2.0-alpha",
    "crypto": "github:jspm/nodelibs-crypto@0.2.0-alpha",
    "events": "github:jspm/nodelibs-events@0.2.0-alpha",
    "fs": "github:jspm/nodelibs-fs@0.2.0-alpha",
    "ionic-angular": "npm:ionic-angular@2.0.0-beta.11-201609011853",
    "ionic-native": "npm:ionic-native@1.3.21",
    "ionicons": "npm:ionicons@3.0.0",
    "mdk-ionic2-lib-core": "mdk:mdk-ionic2-lib-core@master",
    "os": "github:jspm/nodelibs-os@0.2.0-alpha",
    "path": "github:jspm/nodelibs-path@0.2.0-alpha",
    "process": "github:jspm/nodelibs-process@0.2.0-alpha",
    "readline": "github:jspm/nodelibs-readline@0.2.0-alpha",
    "reflect-metadata": "npm:reflect-metadata@0.1.8",
    "rxjs": "npm:rxjs@5.0.0-beta.6",
    "stream": "github:jspm/nodelibs-stream@0.2.0-alpha",
    "string_decoder": "github:jspm/nodelibs-string_decoder@0.2.0-alpha",
    "tty": "github:jspm/nodelibs-tty@0.2.0-alpha",
    "typescript": "npm:typescript@next",
    "util": "github:jspm/nodelibs-util@0.2.0-alpha",
    "vm": "github:jspm/nodelibs-vm@0.2.0-alpha",
    "zone.js": "npm:zone.js@0.6.17"
  },
  packages: {
    "github:jspm/nodelibs-crypto@0.2.0-alpha": {
      "map": {
        "crypto-browserify": "npm:crypto-browserify@3.11.0"
      }
    },
    "github:jspm/nodelibs-os@0.2.0-alpha": {
      "map": {
        "os-browserify": "npm:os-browserify@0.2.1"
      }
    },
    "npm:crypto-browserify@3.11.0": {
      "map": {
        "browserify-cipher": "npm:browserify-cipher@1.0.0",
        "browserify-sign": "npm:browserify-sign@4.0.0",
        "create-hmac": "npm:create-hmac@1.1.4",
        "pbkdf2": "npm:pbkdf2@3.0.4",
        "create-hash": "npm:create-hash@1.1.2",
        "randombytes": "npm:randombytes@2.0.3",
        "create-ecdh": "npm:create-ecdh@4.0.0",
        "diffie-hellman": "npm:diffie-hellman@5.0.2",
        "public-encrypt": "npm:public-encrypt@4.0.0",
        "inherits": "npm:inherits@2.0.3"
      }
    },
    "npm:create-hmac@1.1.4": {
      "map": {
        "create-hash": "npm:create-hash@1.1.2",
        "inherits": "npm:inherits@2.0.3"
      }
    },
    "npm:browserify-sign@4.0.0": {
      "map": {
        "create-hash": "npm:create-hash@1.1.2",
        "create-hmac": "npm:create-hmac@1.1.4",
        "inherits": "npm:inherits@2.0.3",
        "elliptic": "npm:elliptic@6.3.1",
        "browserify-rsa": "npm:browserify-rsa@4.0.1",
        "parse-asn1": "npm:parse-asn1@5.0.0",
        "bn.js": "npm:bn.js@4.11.6"
      }
    },
    "npm:pbkdf2@3.0.4": {
      "map": {
        "create-hmac": "npm:create-hmac@1.1.4"
      }
    },
    "npm:create-hash@1.1.2": {
      "map": {
        "inherits": "npm:inherits@2.0.3",
        "ripemd160": "npm:ripemd160@1.0.1",
        "sha.js": "npm:sha.js@2.4.5",
        "cipher-base": "npm:cipher-base@1.0.2"
      }
    },
    "npm:diffie-hellman@5.0.2": {
      "map": {
        "randombytes": "npm:randombytes@2.0.3",
        "bn.js": "npm:bn.js@4.11.6",
        "miller-rabin": "npm:miller-rabin@4.0.0"
      }
    },
    "npm:public-encrypt@4.0.0": {
      "map": {
        "create-hash": "npm:create-hash@1.1.2",
        "randombytes": "npm:randombytes@2.0.3",
        "browserify-rsa": "npm:browserify-rsa@4.0.1",
        "parse-asn1": "npm:parse-asn1@5.0.0",
        "bn.js": "npm:bn.js@4.11.6"
      }
    },
    "npm:browserify-cipher@1.0.0": {
      "map": {
        "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
        "browserify-aes": "npm:browserify-aes@1.0.6",
        "browserify-des": "npm:browserify-des@1.0.0"
      }
    },
    "npm:create-ecdh@4.0.0": {
      "map": {
        "elliptic": "npm:elliptic@6.3.1",
        "bn.js": "npm:bn.js@4.11.6"
      }
    },
    "npm:evp_bytestokey@1.0.0": {
      "map": {
        "create-hash": "npm:create-hash@1.1.2"
      }
    },
    "npm:browserify-des@1.0.0": {
      "map": {
        "inherits": "npm:inherits@2.0.3",
        "cipher-base": "npm:cipher-base@1.0.2",
        "des.js": "npm:des.js@1.0.0"
      }
    },
    "npm:browserify-aes@1.0.6": {
      "map": {
        "create-hash": "npm:create-hash@1.1.2",
        "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
        "inherits": "npm:inherits@2.0.3",
        "cipher-base": "npm:cipher-base@1.0.2",
        "buffer-xor": "npm:buffer-xor@1.0.3"
      }
    },
    "npm:parse-asn1@5.0.0": {
      "map": {
        "browserify-aes": "npm:browserify-aes@1.0.6",
        "create-hash": "npm:create-hash@1.1.2",
        "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
        "pbkdf2": "npm:pbkdf2@3.0.4",
        "asn1.js": "npm:asn1.js@4.8.0"
      }
    },
    "npm:browserify-rsa@4.0.1": {
      "map": {
        "randombytes": "npm:randombytes@2.0.3",
        "bn.js": "npm:bn.js@4.11.6"
      }
    },
    "npm:elliptic@6.3.1": {
      "map": {
        "bn.js": "npm:bn.js@4.11.6",
        "inherits": "npm:inherits@2.0.3",
        "hash.js": "npm:hash.js@1.0.3",
        "brorand": "npm:brorand@1.0.6"
      }
    },
    "npm:cipher-base@1.0.2": {
      "map": {
        "inherits": "npm:inherits@2.0.3"
      }
    },
    "npm:sha.js@2.4.5": {
      "map": {
        "inherits": "npm:inherits@2.0.3"
      }
    },
    "npm:miller-rabin@4.0.0": {
      "map": {
        "bn.js": "npm:bn.js@4.11.6",
        "brorand": "npm:brorand@1.0.6"
      }
    },
    "npm:des.js@1.0.0": {
      "map": {
        "inherits": "npm:inherits@2.0.3",
        "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
      }
    },
    "npm:hash.js@1.0.3": {
      "map": {
        "inherits": "npm:inherits@2.0.3"
      }
    },
    "npm:asn1.js@4.8.0": {
      "map": {
        "bn.js": "npm:bn.js@4.11.6",
        "inherits": "npm:inherits@2.0.3",
        "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
      }
    },
    "github:jspm/nodelibs-buffer@0.2.0-alpha": {
      "map": {
        "buffer-browserify": "npm:buffer@4.9.1"
      }
    },
    "npm:buffer@4.9.1": {
      "map": {
        "isarray": "npm:isarray@1.0.0",
        "base64-js": "npm:base64-js@1.1.2",
        "ieee754": "npm:ieee754@1.1.6"
      }
    },
    "github:jspm/nodelibs-string_decoder@0.2.0-alpha": {
      "map": {
        "string_decoder-browserify": "npm:string_decoder@0.10.31"
      }
    },
    "github:jspm/nodelibs-stream@0.2.0-alpha": {
      "map": {
        "stream-browserify": "npm:stream-browserify@2.0.1"
      }
    },
    "npm:stream-browserify@2.0.1": {
      "map": {
        "inherits": "npm:inherits@2.0.3",
        "readable-stream": "npm:readable-stream@2.1.5"
      }
    },
    "npm:readable-stream@2.1.5": {
      "map": {
        "inherits": "npm:inherits@2.0.3",
        "isarray": "npm:isarray@1.0.0",
        "string_decoder": "npm:string_decoder@0.10.31",
        "buffer-shims": "npm:buffer-shims@1.0.0",
        "util-deprecate": "npm:util-deprecate@1.0.2",
        "process-nextick-args": "npm:process-nextick-args@1.0.7",
        "core-util-is": "npm:core-util-is@1.0.2"
      }
    },
    "npm:ionic-angular@2.0.0-beta.11-201609011853": {
      "map": {
        "mkdirp-no-bin": "npm:mkdirp-no-bin@0.5.1",
        "colors": "npm:colors@1.1.2",
        "inquirer": "npm:inquirer@0.11.0",
        "q": "npm:q@1.4.1",
        "lodash": "npm:lodash@3.10.1"
      }
    },
    "npm:inquirer@0.11.0": {
      "map": {
        "lodash": "npm:lodash@3.10.1",
        "readline2": "npm:readline2@1.0.1",
        "run-async": "npm:run-async@0.1.0",
        "rx-lite": "npm:rx-lite@3.1.2",
        "chalk": "npm:chalk@1.1.3",
        "strip-ansi": "npm:strip-ansi@3.0.1",
        "ansi-regex": "npm:ansi-regex@2.0.0",
        "ansi-escapes": "npm:ansi-escapes@1.4.0",
        "figures": "npm:figures@1.7.0",
        "cli-cursor": "npm:cli-cursor@1.0.2",
        "through": "npm:through@2.3.8",
        "cli-width": "npm:cli-width@1.1.1"
      }
    },
    "npm:chalk@1.1.3": {
      "map": {
        "strip-ansi": "npm:strip-ansi@3.0.1",
        "escape-string-regexp": "npm:escape-string-regexp@1.0.5",
        "supports-color": "npm:supports-color@2.0.0",
        "has-ansi": "npm:has-ansi@2.0.0",
        "ansi-styles": "npm:ansi-styles@2.2.1"
      }
    },
    "npm:strip-ansi@3.0.1": {
      "map": {
        "ansi-regex": "npm:ansi-regex@2.0.0"
      }
    },
    "npm:readline2@1.0.1": {
      "map": {
        "is-fullwidth-code-point": "npm:is-fullwidth-code-point@1.0.0",
        "mute-stream": "npm:mute-stream@0.0.5",
        "code-point-at": "npm:code-point-at@1.0.0"
      }
    },
    "npm:figures@1.7.0": {
      "map": {
        "escape-string-regexp": "npm:escape-string-regexp@1.0.5",
        "object-assign": "npm:object-assign@4.1.0"
      }
    },
    "npm:cli-cursor@1.0.2": {
      "map": {
        "restore-cursor": "npm:restore-cursor@1.0.1"
      }
    },
    "npm:run-async@0.1.0": {
      "map": {
        "once": "npm:once@1.4.0"
      }
    },
    "npm:has-ansi@2.0.0": {
      "map": {
        "ansi-regex": "npm:ansi-regex@2.0.0"
      }
    },
    "npm:is-fullwidth-code-point@1.0.0": {
      "map": {
        "number-is-nan": "npm:number-is-nan@1.0.0"
      }
    },
    "npm:code-point-at@1.0.0": {
      "map": {
        "number-is-nan": "npm:number-is-nan@1.0.0"
      }
    },
    "npm:restore-cursor@1.0.1": {
      "map": {
        "exit-hook": "npm:exit-hook@1.1.1",
        "onetime": "npm:onetime@1.1.0"
      }
    },
    "npm:once@1.4.0": {
      "map": {
        "wrappy": "npm:wrappy@1.0.2"
      }
    },
    "npm:ionic-native@1.3.21": {
      "map": {
        "rxjs": "npm:rxjs@5.0.0-beta.6"
      }
    },
    "mdk:mdk-ionic2-lib-core@master": {
      "map": {
        "lodash": "npm:lodash@4.15.0"
      }
    }
  }
});
