	platform :ios, '8.0'

	source 'https://github.com/CocoaPods/Specs.git'

	use_frameworks!
	inhibit_all_warnings!

	pod 'MFCore', :path => '../../../mdk-ios-lib-core'
	pod 'MFUI', :path => '../../../mdk-ios-lib-ui'
	pod 'MDKControl', :path => '../../../mdk-ios-control'

	post_install do |installer_representation|
		installer_representation.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
				config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
				if target.name == "Pods-MFUI"
					config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = '$(CONFIGURATION_BUILD_DIR)'
				end
			end
		end
	end
