	platform :ios, '8.0'

	source 'https://github.com/CocoaPods/Specs.git'

	use_frameworks!
	inhibit_all_warnings!

	pod 'MFCore', :path => '../../mdk-ios-lib-core'
	pod 'MFUI', :path => '../../mdk-ios-lib-ui'
	pod 'MDKControl', :path => '../../mdk-ios-control'