	platform :ios, '8.0'

	target 'MFTemplate' do

		use_frameworks!
		inhibit_all_warnings!

		pod 'MFCore', :path => '../../mdk-ios-lib-core'
		pod 'MFUI', :path => '../../mdk-ios-lib-ui'
		pod 'MDKControl', :path => '../../mdk-ios-control'

	  target 'MFTemplateTests' do
	    inherit! :search_paths
	    # Pods for testing
	  end

	end
